# group_vars/windows.yml
ansible_connection: amazon.aws.aws_ssm
ansible_shell_type: powershell
ansible_become: true
ansible_become_method: runas

# Prefer WINDOWS_* ; fallback to TF_VAR_* ; default user Administrator
ansible_user: >-
  {{ lookup('env','WINDOWS_USERNAME')
     | default(lookup('env','TF_VAR_WINDOWS_USERNAME'), true)
     | default('Administrator', true) }}

ansible_password: >-
  {{ lookup('env','WINDOWS_PASSWORD')
     | default(lookup('env','TF_VAR_WINDOWS_PASSWORD'), true)
     | default('', true) }}

ansible_become_user: "{{ ansible_user }}"
ansible_become_pass: "{{ ansible_password }}"
