name: GitHub Flow Deployment

on:
  push:
    branches:
      - main
      - staging
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - staging

jobs:
  deploy-dev:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Terraform environment variables
        run: |
          source Iac/terraform/.env.global.terraform
          source Iac/terraform/.env.dev.terraform
          echo "TF_VAR_aws_region=$AWS_DEFAULT_REGION" >> $GITHUB_ENV
          echo "TF_VAR_key_pair_name=$key_pair_name" >> $GITHUB_ENV
          echo "TF_VAR_terraform_state_bucket=$TERRAFORM_STATE_BUCKET" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::375299695019:role/GitHubActionsTerraformRole
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Deploy to dev
        run: |
          chmod +x ./*.sh
          ENVIRONMENT=dev ./deploy.sh

  deploy-staging:
    if: >-
      (github.event_name == 'push' && github.ref == 'refs/heads/staging') ||
      (github.event_name == 'pull_request' && github.base_ref == 'staging' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Terraform environment variables
        run: |
          source Iac/terraform/.env.global.terraform
          source Iac/terraform/.env.staging.terraform
          echo "TF_VAR_aws_region=$AWS_DEFAULT_REGION" >> $GITHUB_ENV
          echo "TF_VAR_key_pair_name=$key_pair_name" >> $GITHUB_ENV
          echo "TF_VAR_terraform_state_bucket=$TERRAFORM_STATE_BUCKET" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::375299695019:role/GitHubActionsTerraformRole
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Deploy to staging
        run: |
          chmod +x ./*.sh
          ENVIRONMENT=staging ./deploy.sh

  deploy-production:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Terraform environment variables
        run: |
          source Iac/terraform/.env.global.terraform
          source Iac/terraform/.env.prod.terraform
          echo "TF_VAR_aws_region=$AWS_DEFAULT_REGION" >> $GITHUB_ENV
          echo "TF_VAR_key_pair_name=$key_pair_name" >> $GITHUB_ENV
          echo "TF_VAR_terraform_state_bucket=$TERRAFORM_STATE_BUCKET" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::375299695019:role/GitHubActionsTerraformRole
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Deploy to Production
        run: |
          chmod +x ./*.sh
          ENVIRONMENT=prod ./deploy.sh
